### ISSUE TITLE
開発用プレイマットにてCube(toio)が右端まで移動しない（解決済み）

### ISSUE THREAD

**Issue by wawon-akasata** [morikatron/toio-sdk-for-unity#169]
# テスト環境
+ Unity 2019.4.0f1 Personal
+ toio SDK for Unity ver1.2.0
+ macOS Big Sur ver.11.2.3

# したい事
開発用プレイマット裏面の2x2(左上#1,左下#2,右上#5,右下#6)にてx=644, y=250まで移動したい。

# 困っている事
右側に移動するものの、x=407, y=253辺りで停止する。

# 試した事
EventScene.csではx=407より右でも正しく座標を取得出来ている。
Y座標に代入する値を変えてみたが解決せず。
コンソールにエラーは出ていない。

# 使用・変更したスクリプト

使用したスクリプト

```cs:CubeMove.cs
using UnityEngine;

namespace toio
{
    public class CubeMove : MonoBehaviour
    {
        //DeveloperMat 1square(high=43, wide=43.5714285714)
        //https://d2air1d4eqhwg2.cloudfront.net/media/files/1fa512cd-858f-4f77-a3e0-241c1eb8213d.pdf

        CubeManager cubeManager;

        async void Start()
        {
            cubeManager = new CubeManager();
            await cubeManager.MultiConnect(1);
        }

        void Update()
        {
            if (cubeManager.synced)
            {
                cubeManager.navigators[0].Navi2Target(644, 250, maxSpd: 50).Exec();
            }
        }
    }
}
```

不具合修正の為、 https://github.com/morikatron/toio-sdk-for-unity/blob/da2fa42ee6fc9966ed344eca7cdbc83465838e08/toio-sdk-unity/Assets/toio-sdk/Scripts/Simulator/Mat.cs#L65 を"var rect = GetRectForMatType(matType, developerMatType); "に変更。

**Comment by wawon-akasata** [comment]
# 解決策
```cs:CubeMove.cs
using UnityEngine;

namespace toio
{
    public class CubeMove : MonoBehaviour
    {
        //DeveloperMat 1square(high=43, wide=43.5714285714)
        //https://d2air1d4eqhwg2.cloudfront.net/media/files/1fa512cd-858f-4f77-a3e0-241c1eb8213d.pdf

        CubeManager cubeManager;

        async void Start()
        {
            cubeManager = new CubeManager();
            await cubeManager.MultiConnect(1);

            //add~
            foreach (var navi in cubeManager.navigators)
            {
                navi.ClearWall();
                navi.AddBorder(10, 34, 644, 35, 466);      // margin = 10
            }
            foreach (var handle in cubeManager.handles)
            {
                handle.SetBorderRect(new RectInt(34, 35, 644 - 34, 466 - 35), margin: 10);
            }
            //~add
        }

        void Update()
        {
            if (cubeManager.synced)
            {
                cubeManager.navigators[0].Navi2Target(644, 250, maxSpd: 50).Exec();
            }
        }
    }
}
```
//add~から//~addを追加する事により解決した。
AddBorder()とSetBorderRect()の値は使用するマットのx最小,x最大,y最小,y最大に合わせると良い。

# 原因
目標に着けない原因はバグではなく、CubeNavigatorとそれが使ってるCubeHandleとがそれぞれボーダー設定（つまり活動範囲の設定）を持っているから。

既定設定は土俵マットに対応していて、もしマットタイプが切り替えられたり、複数枚合わせて使ったりしたら、その設定とのズレで動けなくなる現象が発生する。

# 他の解決策
組み合わせるマットの座標が断続であっても、全部同じマットであっても、CubeHandleを継承して座標を自分で変換することで、複数枚のマットを跨いて動くことが可能。
サンプル→https://github.com/morikatron/toio-sdk-for-unity/tree/main/toio-sdk-unity/Assets/toio-sdk/Samples/Sample_MultiMat

# まとめ
ボーダー設定（活動範囲）を拡張する事で解決した。

**Comment by MrkKSen** [comment]
ご丁寧にissueを上げて頂いてありがとうございました。
解決できたということで閉めます。
