### ISSUE TITLE
Wallを途中で途切れさせたい

### ISSUE THREAD

**Issue by wawon-akasata** [morikatron/toio-sdk-for-unity#170]
# テスト環境
+ Unity 2019.4.0f1 Personal
+ toio SDK for Unity ver1.2.0
+ macOS Big Sur ver.11.2.3

# したい事
Navi2Targetを使用する際、toioが自動で下図のような赤線を回避するようにしたい。
![issue](https://user-images.githubusercontent.com/59409340/114339654-ac1b5380-9b90-11eb-8495-12055ae06674.png)

# 試した事
AddWall(new Wall(0,1,-250,10))で、y=250にWallを追加でき、Navi2TargetでtoioはそのWallを自動で回避した。
これを活用すれば「したい事」は出来そう。

# 困っている事
しかし、AddWall(new Wall(0,1,-250,10))だと、y=250に,x=∞のWallができる（と思っている。間違ってたらすいません。）
xが有限でなければ途中で途切れる壁は作れない。また、Wallの座標（xとy）も指定しなければいけない。

そもそもAddWall(new Wall())にそんな機能があるのかが分からない。
場合によっては他の方法を考える必要がある。
とりあえず、どんな方法でも「したい事」が出来れば良いです。

**Comment by MrkKSen** [comment]
お問い合わせありがとうございます。
おしゃる通りに現状のWallは無限であるため、使える場面がボーダーのに限られてます。
ということで、今こちらが対応しております。

リリースまでは時間がかかりますので、[対応ブランチ](https://github.com/morikatron/toio-sdk-for-unity/tree/develop_navigator) で有限なWall を試しても良いかと思います。

Wallとナビゲーターの計算結果を可視化する[サンプル](https://github.com/morikatron/toio-sdk-for-unity/tree/develop_navigator/toio-sdk-unity/Assets/toio-sdk/Samples/Sample_VisualizeNavigator)もあります。

※　機能は大体使えるのですが、作業中なのでどんどん変わっていく可能性もあるので、このブランチに基づいてコーディングすると後から互換性問題が出るリスクがある、という点はご了承ください。

※　有限線分なため、Wall(a, b, c, margin) といったコントラクターは適しないため、Wall(x1, y1, x2, y2, margin)などに変わる予定です。

**Comment by wawon-akasata** [comment]
対応ありがとうございます。サンプルを試してみたところ実現できそうです。
ありがとうございました。

**Comment by wawon-akasata** [comment]
解決したので閉めさせて頂きます。
