### ISSUE TITLE
Xcode13環境にてビルドができない

### ISSUE THREAD

**Issue by yoshi3110** [morikatron/toio-sdk-for-unity#228]
## ビルド環境
Unity2020.1.9f1
Xcode13.0
toio SDK for Unity v1.3.1
MacOS 11.6 BigSur

## 現状
Unityでのビルドは成功するが、Xcodeでのビルドは失敗する。

## 試したこと
 Xcodeでのビルドを、Legacy build system と New build systemの両方で試行した。

 New:RxBluetoothKit内でエラー
 Legacy: UnityFrameworkのビルドでエラー

**Comment by ma2bara** [comment]
本件、toio SDK for Unity v1.4.0にて対応いたしました。
情報をお寄せいただき、ありがとうございました。
