### ISSUE TITLE
リアルマルチエージェント接続の問題（MacBLE）

### ISSUE THREAD

**Issue by ongr1996** [morikatron/toio-sdk-for-unity#242]
複数のエージェントで同時に移動機能を利用する際に問題があります。複数のエージェントを同時に制御する例はありますか？ML-Agentsで強化学習モデルを学習させていますが、5つのエージェントに接続した後、モデルを実行すると、同じ動きを再現してしまいます。また、実際のキューブに接続し、TargetPoleの例から以下のコードを使用した場合。
if (this.connectType == ConnectType.Real)
{
    foreach (var c in cubeManager.cubes)
    {
        this.cube.transform.position = this.mat.MatCoord2UnityCoord(c.x, c.y);
        this.cube.transform.rotation = Quaternion.Euler(0, c.angle + 90, 0);
    }
}
接続の問題だと思うのですが、何かお知恵を拝借できれば幸いです。また、できれば各キューブで同じコードを使いたいのですが、キューブマネージャークラスを通して各ハンドルを直接制御することは可能でしょうか？

以下の2つのセットアップを試しました。
CubeManager cubeManager;
    Stage stage;
    Mat mat;
    GameObject cube;
    public ConnectType connectType;

async public override void Initialize()
{
this.stage = GameObject.FindObjectOfType<Stage>();
this.mat = GameObject.FindObjectOfType<Mat>();
this.cube = this.gameObject;
cubeManager = new CubeManager(connectType);
await cubeManager.MultiConnect(5);
}

Version 1:
if (cubeManager.synced)
{
cubeManager.handles[0].Move(actionY * 40, actionX * 40, 100, false);
cubeManager.handles[1].Move(actionY * 40, actionX * 40, 100, false);
cubeManager.handles[2].Move(actionY * 40, actionX * 40, 100, false);
cubeManager.handles[3].Move(actionY * 40, actionX * 40, 100, false);
cubeManager.handles[4].Move(actionY * 40, actionX * 40, 100, false);
}

Version 2:
foreach (var handle in cubeManager.syncHandles)
{
    handle.Move(actionY * 40, actionX * 40, 100, false);
}

**Comment by MrkKSen** [comment]
返答遅くなって申し訳ありません。

- 複数のエージェントを制御する例：
https://github.com/morikatron/toio-sdk-for-unity/blob/main/toio-sdk-unity/Assets/toio-sdk/Samples/Sample_Cross/README_EN.md
※サンプルコードで使われている navigator は内部で handle.Move を呼び出しています。

- キューブマネージャークラスを通して各ハンドルを直接制御することは勿論可能です。
Version 1 も Version 2 も問題ないです。
なので、どういった問題があるか、原因が何なのかを判断できませんので、もう少し具体的な情報をいただけると幸いです。
