### ISSUE TITLE
Specify toio ID in Unity

### ISSUE THREAD

**Issue by Logenleedev** [morikatron/toio-sdk-for-unity#263]
Hi there. I saw that right now the Unity SDK can connect multiple cubes. However, I was wondering can I specify each cubes movement using the id #? 

For example, imagine we have a list Cube[] cubes;

How can I do sth like cubes[0].move, cubes[1].move .....

**Comment by MrkKSen** [comment]
Sorry for late response.
Cube class has an "id" property, which identifies cubes (hardware).
So you could use if-sentence to control a sepcific cube, or just convert the connected Cube[] to a Dictionary<str, Cube> for convenience.
