### ISSUE TITLE
Android Target API 31以降への対応

### ISSUE THREAD

**Issue by neon-izm** [morikatron/toio-sdk-for-unity#265]
現在のGooglePlayStoreはAndroid Target API 31(Android12)以降への対応が必要で、その場合は新しい権限方式に対応する必要があります。

https://developer.android.com/about/versions/12/features/bluetooth-permissions?hl=ja

対応したパッチを送るとしたらこちらのリポジトリにすべきか、元になってる https://github.com/toio/ble-plugin-unity こちらに送るべきでしょうか？ @MrkKSen

**Comment by MrkKSen** [comment]
@neon-izm さん
issueありがとうございます！

unitypackageの運用上の不都合で、当面は [toio/ble-plugin-unity](https://github.com/toio/ble-plugin-unity) が更新されておらず、[toio-sdk-for-unity](https://github.com/morikatron/toio-sdk-for-unity) の内部の実装だけが更新されています。
なので、toio-sdk-for-unity の方にPRしていただけるととてもありがたいです！

**Comment by neon-izm** [comment]
@MrkKSen sanありがとうございます。
[toio/ble-plugin-unity](https://github.com/toio/ble-plugin-unity) のreadmeにoutdated の記載を入れたいですね。

それはそれとして #266 でPRを送りました。相談ポイントがあって恐縮ですが対応お願いします。

**Comment by neon-izm** [comment]
merged
