### ISSUE TITLE
Where latest (Windows | Mac)plugin sources

### ISSUE THREAD

**Issue by neon-izm** [morikatron/toio-sdk-for-unity#269]
このプロジェクト内で使っているWindowsとMacのble plugin sourceは

- https://github.com/toio/ble-plugin-unity/tree/main/bleplugin_projects

- https://github.com/wotakuro/BleGadgetsPluginForUnity/tree/main/ble-plugin-unity

などがあります。iOSやAndroidやWebGLはソースが同梱ということもあってメンテしやすいですが、これらのプラットフォームのプラグインソースをどこかでメンテ可能ですか？

（例えば、Windowsのペリフェラルの切断処理などにバグがある気がしますが、パッチの送り先に悩んでいます）

**Comment by MrkKSen** [comment]
@neon-izm さん
パッチの検討ありがとうございます。
toio/ble-plugin-unity の方でお願いできればと思います！
https://github.com/toio/ble-plugin-unity/tree/main/bleplugin_projects
