### ISSUE TITLE
ビルドできない

### ISSUE THREAD

**Issue by Kanirobo** [morikatron/toio-sdk-for-unity#278]
https://github.com/morikatron/toio-sdk-for-unity/blob/develop/docs/build_web.md
の手順に沿って実施。
「ウェブアプリをビルド」の段階でビルドして実行を行うと、以下のエラーが発生する。

\Assets\toio-sdk\Scripts\BLE\WebGL\BLEWebDevice.cs(21,31): error CS1503: 引数 1: は 'toio.BLEWebPeripheral' から 'toio.BLEPeripheralInterface[]' へ変換することはできません

**Comment by MrkKSen** [comment]
Solved by #279
